# Travis can building for Linux (Ubuntu 14.04 x64) and OS X (El Capitan)
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic

    - os: osx
      sudo: required
      language: generic

before_install:
  # OS and Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then python3 -c "import sys; print(sys.executable)"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo python3 -c "import sys; print(sys.executable)"; fi

install:
  # Python 3 and pip 3 installation depends OS (and for now install PyQt & QScintilla in Linux as well)
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash package/install_osx.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash package/install_linux.sh; fi

  # Install Mu dependencies (PyQt & QScintilla will be absorbed in requirements.txt once ready)
  - sudo pip3 install -r requirements.txt
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install PyQt5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install QScintilla; fi

  # Install packaging dependencies, macOS depends on update not yet release https://github.com/pyinstaller/pyinstaller/pull/1965
  - sudo pip3 install git+git://github.com/pyinstaller/pyinstaller.git@483c819d6a256b58db6740696a901bd41c313f0c

  # Check everything was correctly installed
  - echo $PATH
  - python3 --version
  - python3 -c "import struct; print(struct.calcsize('P') * 8)"
  - python3 -c "import sys; print(sys.executable)"
  - pip3 --version
  - pip3 freeze
  - python3 -c "import PyQt5"
  - python3 -c "import PyQt5.Qsci"

script:
  # Run the tests, at the moment there is a segmentation fault on Linux, this will go away with Py3.5
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make check; fi

  # Package it
  - pyinstaller package/pyinstaller.spec
  - du -sk dist/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv dist/mu dist/mu-$(date '+%Y-%m-%d_%H_%M_%S'); fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd dist && zip --symlinks -r mu-$(date '+%Y-%m-%d_%H_%M_%S').zip mu.app && rm -r mu.app && rm mu && cd ..; fi

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: AKIAJYJV7NN6HVHCX5NQ
  secret_access_key:
    secure: gTy5x7D8J+6VTwR4CY+cxsnV5lGsMYFPoU9kSIwQNvNviZyQDR0Qan+VjUzUa3kvOEVxpBjiA6KkRPtvXslZNgJI8aVzm2GVzEh+9kyDIY3k9LLLy6xpK1q4jFscup+yAhLpgeIVjudp4ClxZy6Q4M28DM/ylAdd3JqiLzwtZr1wYfCa1L075SBqAj+Nj8nP02G2s5kF2hTC5MiQPfAic9jGdiuoFnIs3vN2HpojqZ5sQHBnyeZWX4OWoCSdJdwitdORl25HnFYBzV1vwhqRSgGrW5ssxaF6FEf9nVQMSmxRRvYVRU0lFAmWaTmPNbujsT4/oITXIHnblCD/d3oop5D5clMKkScC7r2v7oF+TcKEJc8IJRQ5eYwhaVhSLIjQmf+P8bZZUhLGHfKUxCl2IC9UjUDwrH7oCy14Le16wVQ+x+tFQKgK4jdZjpT65uRm2bfW+odvxRUiQw2NXoVW9TbXkGmpn7unnlcGB65RVp23oT4gkq2IuGxf+nRa56+N4BybMGxguiT1KG+/lu8P04bjskbrT5SxHQBIpmDRLwSPCZdlTM7+u+ywHxIbl9dhAmSwkqvOYah75VIt4d1PAmPP7pW48hIYIQLSc7ygWoPvZFww+qH8alkmyaHjtUvAe4HHvrQrjvREsYgK3694FBdIsN/BWWUT7rB5Qz/fzF4=
  bucket: ardublockly-builds
  skip_cleanup: true
  local-dir: dist/
  upload-dir: microbit/tests/$TRAVIS_OS_NAME
  acl: public_read
  on:
    repo: carlosperate/mu
    all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
