# Travis can building for Linux and macOS
matrix:
  include:
    - os: linux
      dist: xenial 
      sudo: required
      language: python
      python: 3.5
    - os: linux
      dist: xenial 
      sudo: required
      language: python
      python: 3.6
    - os: linux
      dist: xenial
      sudo: required
      language: python
      python: 3.7

    # To maximise compatibility pick earliest image, OS X 10.12
    - os: osx
      osx_image: xcode8.3
      sudo: required
      language: generic
      python: 3.6

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi
  # Linux packages needed for Qt to work.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libxkbcommon-x11-0; fi
  # Python 3 installation required
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash package/install_osx.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pyenv install 3.6.5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pyenv versions; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pyenv global 3.6.5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "$(pyenv init -)"; fi
  - pip install --upgrade pip setuptools
  # Check everything was correctly installed
  - echo $PATH
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -c "import sys; print(sys.executable)"
  - python -m pip --version
  - pip --version
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then virtualenv venv --python=python3; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source venv/bin/activate; fi

install:
  # Install Mu and its dependencies
  - pip install .[dev]
  # Check everything was correctly installed
  - pip freeze

script:
  # Run the tests on the Linux platform: needs "X Virtual Framebuffer".
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run make check; fi
  - make clean

  # Run the tests on macOS and package it: "make macos" runs checks+tests first.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make macos; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir dist; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then zip -r -X dist/mu-editor.zip macOS/mu-editor.app; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then du -sk dist/; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv dist/mu-editor.zip dist/mu-editor_$(date '+%Y-%m-%d_%H_%M')_${TRAVIS_BRANCH}_${TRAVIS_COMMIT:0:7}.zip; fi

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: AKIAJYJV7NN6HVHCX5NQ
  secret_access_key:
    secure: gTy5x7D8J+6VTwR4CY+cxsnV5lGsMYFPoU9kSIwQNvNviZyQDR0Qan+VjUzUa3kvOEVxpBjiA6KkRPtvXslZNgJI8aVzm2GVzEh+9kyDIY3k9LLLy6xpK1q4jFscup+yAhLpgeIVjudp4ClxZy6Q4M28DM/ylAdd3JqiLzwtZr1wYfCa1L075SBqAj+Nj8nP02G2s5kF2hTC5MiQPfAic9jGdiuoFnIs3vN2HpojqZ5sQHBnyeZWX4OWoCSdJdwitdORl25HnFYBzV1vwhqRSgGrW5ssxaF6FEf9nVQMSmxRRvYVRU0lFAmWaTmPNbujsT4/oITXIHnblCD/d3oop5D5clMKkScC7r2v7oF+TcKEJc8IJRQ5eYwhaVhSLIjQmf+P8bZZUhLGHfKUxCl2IC9UjUDwrH7oCy14Le16wVQ+x+tFQKgK4jdZjpT65uRm2bfW+odvxRUiQw2NXoVW9TbXkGmpn7unnlcGB65RVp23oT4gkq2IuGxf+nRa56+N4BybMGxguiT1KG+/lu8P04bjskbrT5SxHQBIpmDRLwSPCZdlTM7+u+ywHxIbl9dhAmSwkqvOYah75VIt4d1PAmPP7pW48hIYIQLSc7ygWoPvZFww+qH8alkmyaHjtUvAe4HHvrQrjvREsYgK3694FBdIsN/BWWUT7rB5Qz/fzF4=
  bucket: ardublockly-builds
  skip_cleanup: true
  local-dir: dist/
  upload-dir: microbit/tests/$TRAVIS_OS_NAME
  acl: public_read
  on:
    repo: carlosperate/mu
    all_branches: true
    condition: $TRAVIS_OS_NAME = "osx"

notifications:
  email:
    on_success: change
    on_failure: change
