# Travis can building for Linux and macOS
matrix:
  include:
    # To maximise compatibility pick earliest image, Ubuntu 14.04.5 x64
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.5
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.6

    # To maximise compatibility pick earliest image, OS X 10.10 Yosemite
    - os: osx
      osx_image: xcode6.4
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi
  # Python 3 and pip 3 installation required in macOS
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash package/install_osx.sh; fi
  # Linux needs to install pip again to have pip3 for the right Python version
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash package/install_pip3.sh; fi
  # Check everything was correctly installed
  - echo $PATH
  - python3 --version
  - python3 -c "import struct; print(struct.calcsize('P') * 8)"
  - python3 -c "import sys; print(sys.executable)"
  - python3 -m pip --version
  - pip3 --version
  - pip3 install pipenv
  - pipenv --three

install:
  # Install Mu dependencies
  - pipenv run pip install -r requirements.txt
  # Install packager for OSX
  - pipenv install briefcase
  # Install disk image maker for OSX
  - pipenv install dmgbuild
  # Install helpful pytest plug-in
  - pipenv install pytest-faulthandler
  # Check everything was correctly installed
  - pipenv run pip freeze

script:
  # Run the tests
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pipenv run make check; fi
  # PyQt crashes without a frame buffer, so Linux needs "X Virtual Framebuffer"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pipenv run xvfb-run make check; fi
  - make clean

  # Package it for OSX
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo "[install]" >> setup.cfg; echo "prefix=" >> setup.cfg; fi
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo mkdir -p /lib/python3.6/site-packages/; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pipenv run python3 setup.py macos; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir dist; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pipenv run dmgbuild -s package/dmg_settings.py "Mu Editor" dist/mu-editor.dmg; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then du -sk dist/; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv dist/mu-editor.dmg dist/mu-editor_$(date '+%Y-%m-%d_%H_%M')_${TRAVIS_BRANCH}_${TRAVIS_COMMIT:0:7}.dmg; fi

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: AKIAJYJV7NN6HVHCX5NQ
  secret_access_key:
    secure: QHLfRUdFQX+TejhRBkgNvySkaQOskXji+iduIvKRtzvvhyr3QJHKcMNtO426GRFyKhz6sK3shqn4d5iu/m03gtbv+u1pL9pp0J2GEePzQVP8v24q9Y3oxaXaA7Tm7L2vSIrB7uhJvG5D9H0bVL9my61JvXhvySH47jLvhqHH4F9LdPzby1DXds1Z+R4YNMKE0Z4KmNOhiBHkmKdDcp61fZ91gGiScFIjaXvDb50zdGKjXTQy2t4OtFt4kVbTZWijzxKPCSLZkErfcdNNrCNeMEktk6IEV2KVru9XhDNzzslWwwsR1r2hQI39oVULa3fYXK6W7am8WXVZ6cnJB+yBsNWro3Tp5oiNCWSe6fKDEp+Io+qyhZ+R5PSdzhyRYPUHPCIY/fP/dap/4M/MAO3hZFA3mxjK/vUOc6mtMD/wTE659K4/i7PNYtKFndXXpLpYHHaTis44NLZFIxvs9wWG/ljToYDDK20vG317k5TZUZB/6EipW1DeoO/9qBUxgTdfJypp58kcZNvntUVa4ezf/Bx01ZCMFAk234l7+xAFYI7+m9ITqAPlKWI230Ki5ShzyV+kYcI/GS9cT75iok6+zIWWfyQhKUMDYZ1qb/UDM5Gz9RXoIah0UJTjFd4b3bO6Awdrs2V5Vv2EgMWuKDaHs1s3uONH+PGTluROuqFju/s=
  bucket: mu-builds
  region: eu-west-2
  skip_cleanup: true
  local-dir: dist/
  upload-dir: $TRAVIS_OS_NAME
  acl: public_read
  on:
    repo: carlosperate/mu
    branch: [master, package_macos_mine]
    condition: $TRAVIS_OS_NAME = "osx"

notifications:
  email:
    on_success: change
    on_failure: change
