# Travis can building for Linux and macOS
matrix:
  include:
    # To maximise compatibility pick earliest image, Ubuntu 14.04.5 x64
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.5
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.6

    # To maximise compatibility pick earliest image, OS X 10.10 Yosemite
    - os: osx
      osx_image: xcode6.4
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi
  # Python 3 and pip 3 installation required in macOS
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash package/install_osx.sh; fi
  # Linux needs to install pip again to have pip3 for the right Python version
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash package/install_pip3.sh; fi
  # Check everything was correctly installed
  - echo $PATH
  - python3 --version
  - python3 -c "import struct; print(struct.calcsize('P') * 8)"
  - python3 -c "import sys; print(sys.executable)"
  - python3 -m pip --version
  - pip3 --version

install:
  # Install Mu dependencies
  - pip3 install -r requirements.txt
  # Install packaging dependencies
  - pip3 install pyinstaller==3.3.1
  # Install helpful pytest plug-in
  - pip3 install pytest-faulthandler
  # Check everything was correctly installed
  - pip3 freeze

script:
  # Run the tests
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make check; fi
  # PyQt crashes without a frame buffer, so Linux needs "X Virtual Framebuffer"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run make check; fi
  - make clean

  # Package it
  - pyinstaller package/pyinstaller.spec
  - du -sk dist/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv dist/mu dist/mu_$(date '+%Y-%m-%d_%H_%M')_${TRAVIS_BRANCH}_${TRAVIS_COMMIT:0:7}.bin; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd dist && zip --symlinks -r mu_$(date '+%Y-%m-%d_%H_%M')_${TRAVIS_BRANCH}_${TRAVIS_COMMIT:0:7}.zip mu.app && rm -r mu.app && rm mu && cd ..; fi

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: AKIAJYJV7NN6HVHCX5NQ
  secret_access_key:
    secure: gTy5x7D8J+6VTwR4CY+cxsnV5lGsMYFPoU9kSIwQNvNviZyQDR0Qan+VjUzUa3kvOEVxpBjiA6KkRPtvXslZNgJI8aVzm2GVzEh+9kyDIY3k9LLLy6xpK1q4jFscup+yAhLpgeIVjudp4ClxZy6Q4M28DM/ylAdd3JqiLzwtZr1wYfCa1L075SBqAj+Nj8nP02G2s5kF2hTC5MiQPfAic9jGdiuoFnIs3vN2HpojqZ5sQHBnyeZWX4OWoCSdJdwitdORl25HnFYBzV1vwhqRSgGrW5ssxaF6FEf9nVQMSmxRRvYVRU0lFAmWaTmPNbujsT4/oITXIHnblCD/d3oop5D5clMKkScC7r2v7oF+TcKEJc8IJRQ5eYwhaVhSLIjQmf+P8bZZUhLGHfKUxCl2IC9UjUDwrH7oCy14Le16wVQ+x+tFQKgK4jdZjpT65uRm2bfW+odvxRUiQw2NXoVW9TbXkGmpn7unnlcGB65RVp23oT4gkq2IuGxf+nRa56+N4BybMGxguiT1KG+/lu8P04bjskbrT5SxHQBIpmDRLwSPCZdlTM7+u+ywHxIbl9dhAmSwkqvOYah75VIt4d1PAmPP7pW48hIYIQLSc7ygWoPvZFww+qH8alkmyaHjtUvAe4HHvrQrjvREsYgK3694FBdIsN/BWWUT7rB5Qz/fzF4=
  bucket: ardublockly-builds
  skip_cleanup: true
  local-dir: dist/
  upload-dir: microbit/tests/$TRAVIS_OS_NAME
  acl: public_read
  on:
    repo: carlosperate/mu
    all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change
